In [1]:
import pandas as pd
from sklearn import datasets
import numpy as np
import matplotlib.pyplot as plt

In [15]:
iris = datasets.load_iris()
X=iris.data
y=iris.target

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1234,stratify=y)
print(f"X_train:{len(X_train)} X_test:{len(X_test)}")

X_train:100 X_test:50


In [23]:
#Train the SVC
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix

In [25]:
svc = SVC(kernel='rbf',gamma=1.0)

In [26]:
svc.fit(X_train,y_train)

SVC(gamma=1.0)

In [27]:
y_predict = svc.predict(X_test)

In [30]:
cm_rbf01 = confusion_matrix(y_test,y_predict)
cm_rbf01 

array([[16,  0,  0],
       [ 0, 16,  1],
       [ 0,  0, 17]], dtype=int64)

In [31]:
svc.score(X_test,y_test)

0.98

In [33]:
svc = SVC(kernel='rbf',gamma=10.0)
svc.fit(X_train,y_train)
y_predict = svc.predict(X_test)
cm_rbf01 = confusion_matrix(y_test,y_predict)
cm_rbf01 

array([[13,  0,  3],
       [ 0, 14,  3],
       [ 0,  0, 17]], dtype=int64)

In [34]:
#Linear 
svc = SVC(kernel='linear')
svc.fit(X_train,y_train)
y_predict = svc.predict(X_test)
cm_linear = confusion_matrix(y_test,y_predict)
cm_linear

array([[16,  0,  0],
       [ 0, 16,  1],
       [ 0,  0, 17]], dtype=int64)

In [38]:
#Sigmoid
svc = SVC(kernel='sigmoid')
svc.fit(X_train,y_train)
y_predict = svc.predict(X_test)
cm_sig = confusion_matrix(y_test,y_predict)
cm_sig
#for this data we can not use sigmoid

array([[16,  0,  0],
       [17,  0,  0],
       [17,  0,  0]], dtype=int64)

In [37]:
#Polynomial
svc = SVC(kernel='poly')
svc.fit(X_train,y_train)
y_predict = svc.predict(X_test)
cm_poly = confusion_matrix(y_test,y_predict)
cm_poly

array([[16,  0,  0],
       [ 0, 16,  1],
       [ 0,  0, 17]], dtype=int64)